#Add it to $HOME/.basrc like this: . $HOME/dev/projs/scripts/essentials/bashrc

#
# esc . ctrl + e = expand alias
# esc + * = expand autocomplition
#

#has to be set to scripts folder manually
DIR="$HOME/dev/projs/scripts"

#essentials scripts
alias hlp="$DIR/linux/helper.sh"
alias and="$DIR/android/android.sh"
alias proj="$DIR/android/projectTools.sh"
alias mode="$DIR/linux/mode.sh"
alias studio="$HOME/dev/android-studio/bin/studio.sh"

#basic
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias ld='ls -d' #great to filter directories
alias c='clear'

#error correction
alias sl=ls
alias bim='vim'
alias grep='grep --color=auto'

#alert
alias alert='notify-send --urgency=low'

#Android helper
alias paste='adb shell input text'
alias devid="adb devices | tail -n +2 | cut -sf 1"
alias startintent="devid | xargs -I X adb -s X shell am start $1"
alias apkinstall="devid | xargs -I X adb -s X install -r $1"
alias rmapp="devid | xargs -I X adb -s X uninstall $1"
alias clearapp="devid | xargs -I X adb -s X shell pm clear $1"

# gradle
GRADLE="./gradlew --stacktrace --daemon"
ASSEMBLE="assembleDebug"
alias g="$GRADLE"
alias gc="g clean"
alias gd="g $ASSEMBLE"
alias gcd="gc $ASSEMBLE"

# mainframer
alias m="mainframer"
alias mg="m $GRADLE"
alias mgd="mg $ASSEMBLE"
alias mgc="mg clean"
alias mgcd="mgc $ASSEMBLE"

#git
alias gitconfig="git config --global"

